Traceback (most recent call last):
  File "./tools/test_sg_net.py", line 16, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "/rds/user/jm2245/hpc-work/data/OSCAR/scene_graph_benchmark/maskrcnn_benchmark/engine/inference.py", line 16, in <module>
    from scene_graph_benchmark.scene_parser import SceneParserOutputs
  File "/rds/user/jm2245/hpc-work/data/OSCAR/scene_graph_benchmark/scene_graph_benchmark/scene_parser.py", line 11, in <module>
    from .relation_head.relation_head import build_roi_relation_head
  File "/rds/user/jm2245/hpc-work/data/OSCAR/scene_graph_benchmark/scene_graph_benchmark/relation_head/relation_head.py", line 14, in <module>
    from .loss import make_roi_relation_loss_evaluator
  File "/rds/user/jm2245/hpc-work/data/OSCAR/scene_graph_benchmark/scene_graph_benchmark/relation_head/loss.py", line 15, in <module>
    from .contrastive_loss_sample_pairs import add_rel_blobs, add_rel_proposals
  File "/rds/user/jm2245/hpc-work/data/OSCAR/scene_graph_benchmark/scene_graph_benchmark/relation_head/contrastive_loss_sample_pairs.py", line 6, in <module>
    import scipy
  File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/scipy/fft/__init__.py", line 81, in <module>
    from ._helper import next_fast_len
  File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/scipy/fft/_helper.py", line 4, in <module>
    from . import _pocketfft
  File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 8, in <module>
    from . import pypocketfft as pfft
ImportError: /usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/gcc-5.4.0-fis24ggupugiobii56fesif2y3qulpdr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/local/software/master/python/3.8/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
